name: aia1
channels:
  - defaults
dependencies:
  - python=3.7
  - pip:
    - cli-exit-tools==1.2.3.2
    - click==8.0.4
    - dill==0.3.4
    - importlib-metadata==4.8.3
    - lib-detect-testenv==2.0.2.2
    - multiprocess==0.70.12.2
    - typing-extensions==4.1.1
    - wrapt==1.14.1
    - wrapt-timeout-decorator==1.3.12.2
    - zipp==3.6.0
