all:
	clear
	python run.py -src data/input.txt -tar data/pred.txt -tm 2

best:
	python run.py -src data/output.txt -tar data/perf.txt -tm 2

nis:
	python runN.py -src data/input.txt -tar data/pred.txt -tm 2
